name: workflow_env
on:
  workflow_dispatch:


jobs:
  test-secrets:
    environment: config test
    env:
      DB_U: ${{vars.DB_USERNAME}}
      DB_P: ${{ vars.DB_PASSWORD_ON_TEST_ENV }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check env u
        run: echo "u=${{ env.DB_U }}"
      - name: check env p
        run: echo "p=${{ env.DB_P }}"
  pro-secrets:
    environment: production
    env:
      DB_U: ${{vars.DB_USERNAME}}
      DB_P: ${{ vars.DB_PASSWORD_ON_PRO_ENV }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check env u
        run: echo "u=${{ env.DB_U }}"
      - name: check env p
        run: echo "p=${{ env.DB_P }}"
